"""empty message

Revision ID: 0cf6f46de6db
Revises: 6886cb594292
Create Date: 2019-07-03 22:41:36.633772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cf6f46de6db'
down_revision = '6886cb594292'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('city', sa.String(length=100), nullable=False))
    op.add_column('user', sa.Column('introduce', sa.String(length=100), nullable=False))
    op.add_column('user', sa.Column('job', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'job')
    op.drop_column('user', 'introduce')
    op.drop_column('user', 'city')
    # ### end Alembic commands ###
