"""empty message

Revision ID: 4917e55e20d3
Revises: 7116601b1914
Create Date: 2019-06-01 20:19:53.061446

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4917e55e20d3'
down_revision = '7116601b1914'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('anwser', 'create_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('anwser', sa.Column('create_time', mysql.DATETIME(), nullable=True))
    # ### end Alembic commands ###
