"""empty message

Revision ID: 6886cb594292
Revises: 4917e55e20d3
Create Date: 2019-06-01 20:20:16.193078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6886cb594292'
down_revision = '4917e55e20d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('anwser', sa.Column('create_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('anwser', 'create_time')
    # ### end Alembic commands ###
