"""empty message

Revision ID: 7116601b1914
Revises: 9efa14d0bc1c
Create Date: 2019-06-01 20:06:15.449655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7116601b1914'
down_revision = '9efa14d0bc1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('anwser', sa.Column('create_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('anwser', 'create_time')
    # ### end Alembic commands ###
